name: 'Run tests'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        working-directory: '.'
        run: npm install
      - name: Run tests
        working-directory: '.'
        run: npm run test